name: Terraform destroy

on:
  workflow_dispatch:

env:
  HEAD_REPOSITORY: "${{ github.event.pull_request.head.repo.full_name }}"
  HEAD_SHA: "${{ github.event.pull_request.head.sha }}"
  GITHUB_TOKEN: "${{ github.token }}"

permissions:
  id-token: write
  contents: read

jobs:
  terraform_plan:
    name: "Run Terraform"
    runs-on: ubuntu-latest
    steps:
    - name: "🔒️ - Fetch AWS credentials"
      id: "aws-credentialss"
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.EDT_ROLE_TO_ASSUME }}
        aws-region: us-west-2
    - uses: actions/checkout@v3
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
        persist-credentials: true

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.5
        terraform_wrapper: false

    - name: Configure Git Credentials
      run: |
        git config --local --remove-section http."https://github.com/"
        git config --global url."https://${EDT_GITHUB_USER}:${EDT_GITHUB_ACCESS_TOKEN}@github.com/EDT-Partners-Tech".insteadOf "https://github.com/EDT-Partners-Tech"
      env:
        EDT_GITHUB_USER: ${{ secrets.EDT_GITHUB_USER }}
        EDT_GITHUB_ACCESS_TOKEN: ${{ secrets.EDT_GITHUB_ACCESS_TOKEN }}

    - name: terraform init
      id: init
      run: |
        terraform init \
          -input=false \
          -backend-config="bucket=terraform-ai-infra" \
          -backend-config="key=infra.tfstate" \
          -backend-config="region=us-west-2" \
          -backend-config="encrypt=true"

    - name: terraform destroy
      id: destroy
      run: terraform destroy -input=false -compact-warnings -var-file=production.tfvars -auto-approve
